### ISSUE TITLE
Ciclo Hit Id

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#10]
Permitir que os attack coliders possam voltar a atingir novamente caso a anima entre em Loop. Algo como se o loop sempre zerasse os IDs

**Comment by nuzrub** [comment]
Fiz uma alteração pra isso. Favor verificar na próxima build

**Comment by nuzrub** [comment]
Reverti isso. Tava gerando bug em vários ataques.

**Comment by nuzrub** [comment]
Para o caso dos sparks, talvez cada spark devesse ter um ID único e isso seja usado pra diferenciar o dano de dois sparks iguais

**Comment by nuzrub** [comment]
Depois de olhar as coisas com calma, eu consegui ir encontrando os problemas. É uma parada meio técnica, o lance era que se desse hit no frame 1, ele já automaticamente esquecia a hitbox e, durante a própria pausa, já dava hit dnv, dai entrava em loop e travava o game.
Corrigindo isso, vi que também dava problemas com colisores no frame 1 de animações não loop, ai tive de dar um ajustinho tb.
Moral da história, isso pode até resolver outros bugs raros pelo código.
Lado ruim é que alguns golpes tão MUITO fortes agora. Por exemplo, o super normal do chris, que é um loop, tá tirando 65% do HP

**Comment by andreonanim** [comment]
Magavilhoso
