### ISSUE TITLE
Corvos Saulo B

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#11]
O alpha solto do Saulo B libera dois corvos que só funcionam uma vez. Isso acontece, penso eu, porque não estão sendo eliminados ao sair da câmera. Permitir que ou exista um On Death Sparks out Camera ou (O que acho mais adequado) um a cada vez que apertar o input, os corvos vem com Ids zerados e prontos para novos hits

Edit 1 : Quando faço algum movimento com hit (soco fraco, por exemplo) os corvos tornam a contar hit

**Comment by nuzrub** [comment]
Eu preciso que tu me explique como reproduzir isso. Qual ataque é esse pra eu testar aqui?

**Comment by andreonanim** [comment]
Alpha solto do saulo B

**Comment by andreonanim** [comment]
Colar o Saulo B na parede junto ao adversário e fica apertando Alpha solto sem parar

**Comment by nuzrub** [comment]
Eu adicionei IDs nos sparks, agora ambos acertam

**Comment by andreonanim** [comment]
Aparentemente resolveu
