### ISSUE TITLE
Reações Inesperadas - Damage

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#12]
![image](https://user-images.githubusercontent.com/66812722/86513409-5edbab80-bde0-11ea-9fd7-342828fee2f2.png)
Essas animas quando atingidas estão reagindo como se fosse em pé e não abaixadas
![ReacaoErrada](https://user-images.githubusercontent.com/66812722/86513497-1ec8f880-bde1-11ea-87f8-cab4d43c7425.gif)

**Comment by nuzrub** [comment]
Corrigido. Verificar na próxima build

**Comment by andreonanim** [comment]
Resolvido
