### ISSUE TITLE
Gana Drain

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#13]
O penetra tem um golpe que ele "Rouba" Gana. É preciso criar uma maneira em que, per frame, o adversário tenha sua gana drenada e transferida para o Player 1

Atualmente, temos o modo de charge de gana da Nathy. Seria possível realizar o drain criando um "remover gana" do adversário. Aí era só pôr os dois. O problema desse é que se o adversário não tiver gana, o player irá encher a gana de todo jeito e isso não deve acontecer. Ele deve sugar "apenas o que tem".

**Comment by nuzrub** [comment]
Já foi implementado e testado.
