### ISSUE TITLE
Sistema - Switch Defesa

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#14]
Situação. Personagem que leva ataque e entra em block confirm, é pra defender automaticamente outros golpes mesmo que sejam feitos em outro estado. Tipo, caba atacou em pé e depois abaixado. Se estiver no block confirm ainda, ele defende tanto em pé quanto abaixado sem precisar fazer nada. Visualmente falando a personagem fica em pé mesmo. Mas o block confirm defende tudo.  No block stun, quem recebeu o golpe terá de acionar o input de defender abaixado pra defender também.

**Comment by nuzrub** [comment]
Tu me explicou que é pra no block confirm qualquer outro dano funcionar como um autoblock.
1) isso tira barra de guard?
2) me diz como q eu posso testar isso. Que ataque serve?

**Comment by andreonanim** [comment]
1 - sim.
2 - Coloca na lucy 100 o Pausa given on Defense 80. Coloca o P2 em defesa Stand. Ataca. Aí o adversário ficará preso no block confirm quando tu atacar. Se abaixa com a Lucy e ataca. É pra defender o golpe

**Comment by nuzrub** [comment]
Implementadas ambas as coisas:
1) agora o block confirm funciona como uma forma de invencibilidade temporária, reagindo como um quase-autoblock, sendo a diferença que o personagem não pisca verde.
2) agora, durante o block stun no chão, é possível alterar entre defesa em pé e abaixado

**Comment by andreonanim** [comment]
Perfeito
