### ISSUE TITLE
Sistema - Priority Damage

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#15]
https://docs.google.com/document/d/1uC64I6UnItm34czcMJ4bG5EgUtGb3iJHKu5czxnnOr4/edit

**Comment by nuzrub** [comment]
? O que que tem de errado nesse doc?

**Comment by andreonanim** [comment]
Eu não sabia se marcaria bug ou documentation. Mas por exemplo, reações de prioridades em efeitos é um exemplo

**Comment by nuzrub** [comment]
Usar a issue #67
