### ISSUE TITLE
On Input Spark

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#17]
![image](https://user-images.githubusercontent.com/66812722/89745598-67806b00-da8b-11ea-8889-86682418a4ea.png)
Não consigo explicar melhor que isso. É pra fazer o Baixo beta funcionar no saulo B no movimento do Beta aéreo 

https://docs.google.com/document/d/1ggj4DBdFDdoOOb3-XwhfB2PgZCid-syIDpA5n8gdHew/edit

**Comment by nuzrub** [comment]
A ideia é fazer a lógica com animation bound e um DieOnInput no spark, como combinado no whatsapp.
Testar na próxima build

**Comment by andreonanim** [comment]
O comando funciona, mas a aplicação DieOnInput não funciona pro problema do saulo :( Será preciso um Inverse Bound . Irei abrir um novo issue só pra registro
