### ISSUE TITLE
First Enable Bug

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#18]
![image](https://user-images.githubusercontent.com/66812722/89745645-a4e4f880-da8b-11ea-84ba-bbaa07d60e55.png)
First enable não está funcionando no OnHitConfirm 

Movimento : Super solto Saulo B 

https://docs.google.com/document/d/1ggj4DBdFDdoOOb3-XwhfB2PgZCid-syIDpA5n8gdHew/edit

**Comment by nuzrub** [comment]
É pra tar corrigido na próxima build

**Comment by andreonanim** [comment]
Não corriged :(

**Comment by nuzrub** [comment]
Pode me dizer algo mais jovem? tipo qual ataque n ta funcionando?

**Comment by andreonanim** [comment]
Eu fiz um teste com a lucy mesmo. Tinha colocado o baixo Beta dela (aquelas rabada tudo) e dito que o first enable era o 9. Que se atingisse depois do frame 9, iria para um node qualquer (Criei um que faz ela saltar). Mas aí no primeiro hit já constava como válido, o que não deveria.

**Comment by nuzrub** [comment]
Eu acho que tu fez errado. Aqui eu testei e consegui implementar isso de boa.

**Comment by andreonanim** [comment]
Hm, deu certo mesmo agora...
