### ISSUE TITLE
Sistema - A morte da gravidade

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#19]
Quando um spark encosta no chão, a gravidade e impulses em Y, que podem estar sendo aplicada no código, simplesmente morre. Exemplo : Super aéreo do Saulo B 

Spark UrubuAttackDiagonalSuper (Desce corvo em diagonal)

Spark UrubuAttackAereoSuper (O que deveria subir mas é impedido pelo contato ao solo)

**Comment by nuzrub** [comment]
![image](https://user-images.githubusercontent.com/4140686/91622082-e02c6600-e96b-11ea-965c-c57f9dbda7a7.png)
Tá nascendo o segundo, mas ele nasce com impulso e gravidade zerado

**Comment by nuzrub** [comment]
Ó, quando a gravidade tá empurrando pro chão, faz sentido q ela seja desligada (junto com a velocidade y).
Eu coloquei pra que caso a gravidade seja pra cima, ele não ignora e continua calculando, mas tu tem que tomar cuidado pq o spark pode passar alguns frames fora da cena.

**Comment by andreonanim** [comment]
Sucesso
