### ISSUE TITLE
Contato Solo Spark Born

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#20]
Por algum motivo sparks que atingem o chão tem certa "randomização" de onde nascem 

![Bala](https://user-images.githubusercontent.com/66812722/89795653-06927a80-daff-11ea-91cf-ea7d87f96a84.gif)

**Comment by nuzrub** [comment]
Preciso que tu crie pra mim uma forma de reproduzir isso com o fraco no ar da Lucy e me mostre um gif do problema

**Comment by andreonanim** [comment]
Done

**Comment by andreonanim** [comment]
![image](https://user-images.githubusercontent.com/66812722/91484931-5ce21600-e880-11ea-9533-1be6c4314eb5.png)
não é pra nascer em B mas sim em A

**Comment by nuzrub** [comment]
Corrigido pro solo e pra parede
