### ISSUE TITLE
Gana Drain

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#23]
Penetra tem um movimento que Tira Gana do adversário e passa para ele. É preciso se atentar ao fato de "se a gana acabar, o node se encerra". O movimento é o Beta Baixo. Mas é preciso ser atingido por ser um counter

**Comment by nuzrub** [comment]
![image](https://user-images.githubusercontent.com/4140686/91885382-0d279400-ec5e-11ea-8000-235f35866994.png)

**Comment by nuzrub** [comment]
Ai eu adicionei o OpponentGanaPerFrame, isso te permite fazer o oponente GANHAR gana (valor positivo) ou PERDER gana (valor negativo)
Dai tem 4 transições novas, baseadas em encheu gana, secou gana, oponente encheu gana, oponente secou gana

**Comment by andreonanim** [comment]
Funcionando lindamente. Ajustar na nathy logo
