### ISSUE TITLE
Cancelamento Sem Custos de Gana

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#28]
Uma nova categoria de cancelamento onde ele respeita todas as propriedades dos cancelamentos normais, com exceção de não piscar nem ter um custo de cancelamento

**Comment by nuzrub** [comment]
Implementado como
"CancelableWith_NoHitConfirm_NoCost": [...]

e
"CancelableWith_HitConfirm_NoCost": [...]

**Comment by andreonanim** [comment]
Com exceção do super, funciona perfeitamente. Os supers continuam sendo possíveis de serem executados apenas no level 2+

**Comment by nuzrub** [comment]
É pra funcionar na próxima build.

**Comment by nuzrub** [comment]
Falta só tu implementar no penetra né :x

**Comment by andreonanim** [comment]
Funcionando perfeitamente :)
