### ISSUE TITLE
Movimentos usáveis via cancelamento

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#30]
Ter a possibilidade de existirem extraspell com seus inputs normais. No entanto, só serem possíveis de executar via Cancelamento.

**Comment by nuzrub** [comment]
"CancelOnly": True
Testar qnd tiver a build

**Comment by andreonanim** [comment]
"ygor disse: tentar colocar a lógica de cancelamento junto com o input"


Os demais situações funcionam.

**Comment by nuzrub** [comment]
Cara, eu testei aqui e funciona. Que ataque tá dando problema contigo pra eu testar aqui?

**Comment by andreonanim** [comment]
Funcionaram bem em todos os testes. Parabéns. Podemos avançar com a Claudia agora :)
