### ISSUE TITLE
Reformas do Onofre - Voadoras Anti Loop

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#32]
Implementar esse sistema de voadora para resolver problemas com loops

https://docs.google.com/document/d/188whENF0l3BeCc3gT2amP3PbvWOiUuZr153qU6LYry4/edit

**Comment by nuzrub** [comment]
Nota para si: incluir constraint prum ataque só poder ser feito em animações X e, com isso, aplicar esses golpes "caso especial" por meio do sistema de prioridades de ataque. Conferir documentação pra ver se resolve

**Comment by nuzrub** [comment]
@andreonanim 
Agora dá pra colocar ""RequiresAnimations": [20, 21]," num ataque. Isso faz com que ele só possa ser usado se o personagem estiver em uma certa animação. Fica antes do InitialNode, como na foto abaixo:
![image](https://user-images.githubusercontent.com/4140686/100033850-bc958200-2dd9-11eb-9ec3-401a4e172d54.png)

Para fazer as voadoras especiais, basta criar uns ExtraNormalAttack que vem DEPOIS da voadora normal e requerem animações específicas.
Esperando feedback na próxima build

**Comment by andreonanim** [comment]
O sistema funciona. preciso apenas configurar os personagens todos

Nota: Quando eu coloco um 0 na frente do número (021) curiosamente inverte o sistema. Passa a executar em qualquer pulo, menos o 21
