### ISSUE TITLE
On Block Confirm X On Hit Confirm x On Body Confirm x On Choque Confirm

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#33]
Por como prioridade o Block confirm.

**Comment by andreonanim** [comment]
Atualizei. É preciso também adicionar um On Body Confirm. A diferença desse pro On Hit confirm é que o Hit confirm funciona pra qualquer coisa, o Body Confirm funciona exclusivamente se pegar na caixa azul. 

Prioridades ordem 

1 Block Confirm
2 Choque Confirm
3 Body Confirm
4 Block Confirm
5 hit confirm

**Comment by nuzrub** [comment]
Ué, qual é a caixa q não é azul e também não é de defesa ou choque?

**Comment by andreonanim** [comment]
Bom, temos a caixa de body (a que recebe dano), defesa, counter (que
imagino que seja a de defesa, mas eu mesmo coloco o efeito via json na
personagem), a de choque de ataque. O node de hit confirm funciona pra
todos aí genericamente, pelo que vi.

**Comment by nuzrub** [comment]
Quando que a body é realmente necessária?

**Comment by nuzrub** [comment]
Consertei as prioridades, falta o body (depois q tu me explicar melhor isso)

**Comment by nuzrub** [comment]
Eu separei aqui cada tipo de confirm e criei o any. Fica assim, em ordem de prioridade:

1. OnClashConfirm, ativa quando há choque de ataques (Maior prioridade)
2. OnCounterConfirm, ativa nos golpes da Lucy B
3. OnBlockConfirm, ativa na defesa
4. OnGrappleConfirm, ativa nos agarrões
5. OnHitConfirm, ativa nos danos normais (antes era em qualquer coisa)
6. OnAnyConfirm, ativa em qualquer confirm, funciona como o hitconfirm de antes (Menor prioridade).

Eu atualizei todos os OnHitConfirms existentes para OnAnyConfirm.
Os agarrões agora tu pode trocar para OnGrappleConfirm, para diferenciar em casos que dá pra ter um hit confirm normal. Não sei se existe no jogo, mas preferi deixar separado logo.

**Comment by andreonanim** [comment]
sucesso demais, bb
