### ISSUE TITLE
Claudia Spark 

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#34]
A claudia tem uma magia que irá influenciar no player. Quando essa magia atingir a player, a anima dela muda.

**Comment by nuzrub** [comment]
Como é essa magia, não daria pra implementar como parte dela não?

**Comment by andreonanim** [comment]
Só se o Hit confirm do spark influenciasse na player, como acontecia antes.

**Comment by nuzrub** [comment]
Eu digo, implementar a shuriken como parte da animação da cláudia, num bloco só. Sem ter um spark de verdade.

**Comment by andreonanim** [comment]
Nem eu lembro o que é isso kk
