### ISSUE TITLE
Cancelamentos Cristianos 

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#38]
![image](https://user-images.githubusercontent.com/66812722/91645900-e2e89300-ea1f-11ea-9f33-d03c094954d5.png)

**Comment by nuzrub** [comment]
Tu pode colocá-los? Eu sei que não vai funcionar, mas já ajuda deixar eles todos implementados

**Comment by andreonanim** [comment]
posso

**Comment by nuzrub** [comment]
Ó, eu testei aqui colocando pra nao precisar de hit confirm e ajeitei o que tava errado. Agora tá funcionando.
Entretanto, o frente forte no ar tem um impulsão que quando mistura com o fraco ele corre metade do cenário kkk. É contigo ai olhar o impulso que tem de dar no começo do weak pra ficar direito (ou criar um extra q lide com isso).

**Comment by andreonanim** [comment]
Bom, a solução é de fato pôr um extra. Mas aparentemente é assim mesmo que o onofre quer. Fechando aqui
