### ISSUE TITLE
Saulos Cancelamentos

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#39]
![image](https://user-images.githubusercontent.com/66812722/91645907-f4319f80-ea1f-11ea-93c8-7da474e2cbca.png)

**Comment by nuzrub** [comment]
Tu pode colocá-los? Eu sei que não vai funcionar, mas já ajuda deixar eles todos implementados

**Comment by nuzrub** [comment]
Todos os cancelamentos funcionando agora.
O beta tem que ajeitar a janela que permite o cancelamento.

**Comment by andreonanim** [comment]
Nice and done
