### ISSUE TITLE
Efeito gradativo

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#42]
![image](https://user-images.githubusercontent.com/66812722/91645936-57bbcd00-ea20-11ea-9255-797ffd7a78c2.png)

**Comment by nuzrub** [comment]
Criei uma tag "visual" para os pedidos que não são relacionados com gameplay

**Comment by nuzrub** [comment]
Implementado. Funciona pra palette e ramp
![image](https://user-images.githubusercontent.com/4140686/99197043-a6028180-276e-11eb-8c98-141424dd7afc.png)

**Comment by nuzrub** [comment]
Aguardando feedback

**Comment by andreonanim** [comment]
Magnífico
