### ISSUE TITLE
Transformar transições em eventos

### ISSUE THREAD

**Issue by nuzrub** [trajes-fatais/bugtracker#44]
Permitir chamar eventos como Sparks e Shakes nas transições sem necessariamente ir prum outro node

**Comment by nuzrub** [comment]
Quando a transição não tem Goto ou ela tem "Goto": "Stay", ela não muda de nó.
Agora dá pra por Sparks, Sounds, Shake, Impulse e Impulse_P2
![image](https://user-images.githubusercontent.com/4140686/92337374-83bdfa80-f07f-11ea-8c73-e9a7ef2ad413.png)

**Comment by nuzrub** [comment]
O que tu quer fazer é só fazer que nem tá ai, mas no lugar de OnInput será OnAnyConfirm

**Comment by andreonanim** [comment]
Funcionou. No entanto, o shake que acontece no OnAnyConfirm que eu quero, deve executar junto ao "shake/pausa" do personagem e não depois, como acontece

**Comment by nuzrub** [comment]
Isso dai ja é outra coisa, vou dar fechar e abrir outra
