### ISSUE TITLE
Last For Bug

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#53]
Os sparks que morrem sozinhos (arquivo fechando) só geram filhos se tiverem last for 

![image](https://user-images.githubusercontent.com/66812722/96651371-11416b00-130b-11eb-8c83-a0a16f4f00d1.png)

lembrar de tirar

**Comment by nuzrub** [comment]
Corrigido, esperando feedback

**Comment by andreonanim** [comment]
Makiabel está bugado. Por hora não posso verificar

**Comment by andreonanim** [comment]
Corriged
