### ISSUE TITLE
Priority Death Sparks

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#6]
![image](https://user-images.githubusercontent.com/66812722/86477508-f082e480-bd1e-11ea-8147-8b4281c3888d.png)

Spark quando entra em contato com o solo executa a configuração de OnDeath normal. No entanto, quando se remove a OnDeath a do solo passa a funcionar.

Exemplo : Baixo Beta Ar Nathy

Procurar no Sparks Nathy pelo nome - 
"BetaAirBaixo":

**Comment by nuzrub** [comment]
Achei e corrigi. Verificar na próxima build

**Comment by andreonanim** [comment]
Resolvido
