### ISSUE TITLE
Defesa projétil - Altura

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#60]
Alguns projéteis (tipo os corvos do saulo) devem ser defendidos com base na altura. Exemplo, se estiver em uma altura menor que X, a defesa é pra ser feita abaixada. Se estiver acima ou igual de X, é pra defender em pé. Nota, no geral é sempre possível defender saltando.

Importante: Esse sistema tem prioridade em cima do que já tem no colisor:
![image](https://user-images.githubusercontent.com/66812722/99191372-21ead280-274b-11eb-8b89-f891976825e7.png)

Penso que seja interessante colocar isso no arquivo json do projétil.

**Comment by nuzrub** [comment]
Implementado, aguardando feedback

**Comment by andreonanim** [comment]
Perfeito
