### ISSUE TITLE
Reformas do Onofre - Knocked Attacks em relação ao player

### ISSUE THREAD

**Issue by nuzrub** [trajes-fatais/bugtracker#66]
Colocar os KnockedForwardAttack e KnockedBackward attack para ativarem em relação ao forward/backward do player e não em direção ao oponente.

**Comment by nuzrub** [comment]
Eu fiz a troca e tirei o autocorrect. Entretanto, a animação 992, do KnockedBackwardAttack foi feita flippada na mão, na ferramenta. Dai fica com um flip errado. Será necessário corrigir essa animação em cada personagem

**Comment by nuzrub** [comment]
@andreonanim eu falei com o Onofre e ele acha q a forma mais simples é por um sideeffect de flip nas animações que precisa flipar. Tu pode dar uma olhada nisso?

**Comment by andreonanim** [comment]
Uma coisa curiosa acontece. 
![image](https://user-images.githubusercontent.com/66812722/99213429-65295d80-27ac-11eb-87bf-e72afca630dc.png)
Personagem knocada
Pressiono pra ela levantar atacando
![image](https://user-images.githubusercontent.com/66812722/99213478-868a4980-27ac-11eb-863a-82eb864135c0.png)
O primeiro quadro ela tá assim. Já o segundo está assim :
![image](https://user-images.githubusercontent.com/66812722/99213497-92760b80-27ac-11eb-9b0a-a18289876cc4.png)

Imagino que deva ser necessário remover o autocorrect

**Comment by nuzrub** [comment]
Esperando feedback da #69

**Comment by nuzrub** [comment]
Adicionados todos os flips necessários. Verificar na próxima build

**Comment by andreonanim** [comment]
Resolved. Topper
