### ISSUE TITLE
Flip na 992 e 990. Rever inputs na 974

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#69]
A animação 992 e 990 quando acionadas, estão executando com um flip. É interessante verificar a situação da 974 vinda de uma rasteira (baixo forte) e a 974 vinda do agarrão frente. A animação mais correta é a do Lourenço

**Comment by andreonanim** [comment]
Houve uma pequena atualização nisso. Talvez ajude : https://docs.google.com/document/d/1bimZva5fFo_W4OpQESAX2EOebYMKQmVHLrdVwqLTbkE/edit

**Comment by nuzrub** [comment]
Tu pode conferir pra mim se todas as animações 990 e 992 estão **na ferramenta** corretas em relação à cabeça da 974?

**Comment by andreonanim** [comment]
Estão corretos, @nuzrub

**Comment by nuzrub** [comment]
Conferido
