### ISSUE TITLE
Projétil Agarrão

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#7]
O Saulo realiza um projétil que ao atingir o adversário, ele fica em uma animação de "preso". Sem poder realizar nenhum comando até que o tempo desta se esgote.

Note: Acredito que acrescentar uma nova itensidade onde esta faz executar uma animação X seja uma solução. No entanto, me pergunto como será o comportamento se atingido no AR. 

![image](https://user-images.githubusercontent.com/66812722/86478368-8cf9b680-bd20-11ea-9455-88180a531893.png)

**Comment by andreonanim** [comment]
Also, https://docs.google.com/spreadsheets/d/1C_ZU0QJiKDSjldM6r7u6RqbkbmgUTelPpCRelhcoatk/edit#gid=0 Segue doc com a nova intensidade

**Comment by nuzrub** [comment]
Implementado, esperando feedback

**Comment by andreonanim** [comment]
Funcionou. Mas acabei de perceber um prob : 
![Grapple](https://user-images.githubusercontent.com/66812722/99216907-95c1c500-27b5-11eb-90dd-14c753471c51.gif)

Como pode ver, será interessante existir um "followAnchorOpponent". Fora isso, está perfeito
