### ISSUE TITLE
Efeitos de paleta / rampa com mais ou menos de 6 cores

### ISSUE THREAD

**Issue by nuzrub** [trajes-fatais/bugtracker#72]
Isso permite criar efeitos que mudam de cor ou que tem momentos sem cor

**Comment by nuzrub** [comment]
Exemplo completo

![image](https://user-images.githubusercontent.com/4140686/99327981-e854bd00-2859-11eb-98ac-9fccf16f25d8.png)

**Comment by andreonanim** [comment]
topper
