### ISSUE TITLE
Cadastrar inimigos fixos do modo arcade

### ISSUE THREAD

**Issue by nuzrub** [trajes-fatais/bugtracker#74]
Colocar nos parâmetros de cada personagem, logo nas primeiras linhas, as seguintes informações.
Exemplo: Lucy
"ArcadeBoss": "Makiabel"
"ArcadeSubBoss": "Lucy_B"
"ArcadeEnemy": "Chris"

Exemplo: Saulo_B
"ArcadeBoss": "Makiabel"
"ArcadeSubBoss": "Saulo"
"ArcadeEnemy": "Lourenço_B"

**Comment by andreonanim** [comment]
Coloquei os nomes. Avisando que o do Makiabel não coloquei nenhum. 

Also, corrigi os nomes dos personagens. Não são mais tipo "lourenço_B" e sim "Sombra"

**Comment by nuzrub** [comment]
Vou ter que rever isso, já que vocês inventaram de mudar o nome dos personagens. Terei de reverter pros nomes originais, que são os nomes oficiais da implementação.
Só o "Name" e "Full Name" definem os nomes "fantasia" que aparecem na UI

**Comment by nuzrub** [comment]
Eu fiz as correções que faltava. Terminado
