### ISSUE TITLE
Saulo B Queda Guiada

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#8]
O saulo B tem esse movimento aqui  : 
![image](https://user-images.githubusercontent.com/66812722/86480289-165eb800-bd24-11ea-9a93-1f5f34006331.png)

Neste move, o player é pra ter a possibilidade de controlar a queda dele indo pra frente ou pra trás, tal qual o chris.

Nota pessoal: Eu consigo imaginar uma maneira de fazer ele ir pra frente ou pra trás usando o "onRealese". Mas o problema está em "Como fazer ele acelerar e alcançar limite de velocidade tal qual o Chris ?"

**Comment by nuzrub** [comment]
Pelo que eu entendi, o Onofre topou que seja de outra maneira e por hora é esperar ver se tu consegue fazer dessa outra maneira.
Enquanto isso vou marcar como wontfix

**Comment by nuzrub** [comment]
@andreonanim tu resolveu, posso fechar a issue?

**Comment by andreonanim** [comment]
Pode
