### ISSUE TITLE
Projétil Adversário Anchor

### ISSUE THREAD

**Issue by andreonanim** [trajes-fatais/bugtracker#9]
Poder controlar se o Projétil irá surgir no Anchor do Player ou Opponent

O Saulo B terá um projétil que ao atingir o adversário, ele deverá aparecer em lugares específicos em cada personagem. Imagino que seja necessário um Anchor no adversário e que seja possível dizer "Tal projétil irá surgir no Anchor do Adversário".

**Comment by nuzrub** [comment]
Implementado como GrappleAnchorOpponent, verificar na próxima build

**Comment by andreonanim** [comment]
De fato o spark surge apenas quando o adversário tem um Anchor. Mas não está surgindo na posição que deveria. 
![image](https://user-images.githubusercontent.com/66812722/89659848-d8b2f900-d8a6-11ea-9525-02b30f83ceb9.png)
Criei um sparkeffect na lucy ataque fraco e coloquei um anchor no chris (anima 02) pra testes

**Comment by nuzrub** [comment]
ele apareceu no canto certo do personagem errado, isso?

**Comment by andreonanim** [comment]
Aparentemente

**Comment by nuzrub** [comment]
Ajeitei, era só uma besteirinha

**Comment by andreonanim** [comment]
Resolvido
